<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>$(MSBuildProjectName.Replace("-", "_"))</RootNamespace>
		<Authors>NF Software Inc.</Authors>
		<Company>NF Software Inc.</Company>
		<Copyright>Copyright 2026 $(Company)</Copyright>
		<Version>10.0.2</Version>
		<AssemblyVersion>10.0.2.0</AssemblyVersion>
		<FileVersion>10.0.2.0</FileVersion>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>IDE0130</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.*" />
		<PackageReference Include="xunit.v3" Version="3.2.*" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Easy-Core\Easy-Core.csproj" />
	</ItemGroup>

</Project>
